# Generated by Django 5.2.6 on 2025-11-26 02:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_nombre',
            field=models.CharField(default='cliente desconocido', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_red_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='descripcion_solicitud',
            field=models.TextField(blank=True, verbose_name='descripcion de la solicitud'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_requerida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha requerida'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('APROBADO', 'Aprobado'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('SOLICITADO', 'Solicitado')], default='SOLICITADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='PedidoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='pedidos/referencia/')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.pedido')),
            ],
        ),
    ]
