# Generated by Django 5.2.8 on 2025-12-02 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_pedido_cliente_email_pedido_medio_contacto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='insumo',
            options={'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedidoimagen',
            options={'verbose_name': 'Imagen de Pedido', 'verbose_name_plural': 'Imágenes de Pedido'},
        ),
        migrations.AlterModelOptions(
            name='plataformaorigen',
            options={'verbose_name': 'Plataforma de Origen', 'verbose_name_plural': 'Plataformas de Origen'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productoimagen',
            options={'verbose_name': 'Imagen de Producto', 'verbose_name_plural': 'Imágenes de Producto'},
        ),
        migrations.AddField(
            model_name='insumo',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='token_seguimiento',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='descripcion_solicitud',
            field=models.TextField(blank=True, verbose_name='descripción de la solicitud'),
        ),
        migrations.AlterField(
            model_name='pedidoimagen',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='mainApp.pedido'),
        ),
    ]
