# Generated by Django 5.2.8 on 2025-11-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='medio_contacto',
            field=models.CharField(blank=True, choices=[('WHATSAPP', 'WhatsApp'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('PRESENCIAL', 'Presencial'), ('SITIO_WEB', 'Sitio Web'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('APROBADO', 'Aprobado'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('SOLICITADO', 'Solicitado'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado')], default='SOLICITADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('PARCIAL', 'Parcial')], default='PENDIENTE', max_length=20),
        ),
    ]
